image: Ubuntu2004
platform: x64
stack: node lts/*

init:
  - node --version
  - npm --version
  - npm install -g codecov

install:
  - npm install

test_script:
  - npm test

build_script:
  - npm run build
  - codecov

# build: off