image: Ubuntu2004
platform: x64
environment:
  - nodejs_version: 'lts'

init:
  - node --version
  - npm --version

install:
  - npm install
  - npm install -g codecov
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

test_script:
  - npm test

build_script:
  - npm run build
  - codecov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# build: off